### ISSUE TITLE
K3S Odoo and IoTBox pods in CrashLoopBackOff

### ISSUE THREAD

**Issue by modonovan** [tobru/odoo-pos-distribution#1]
Hi there,

Fabulous work on this project. I've decide to try and replicate this on a raspberry pi4 myself again as a project for a good friend of mine who's opening a new independent retail store shortly.

I decided I'd go this route as I'm a total newbie to Docker or Kubernetes (k3s) but very keen to learn about one or other or both.

Am I correct in my assumption that it's either Docker or Kubernetes and that you've gone the k3s route? I've the "kubectl apply -f deployment/" on a clone version of the repo and all seems to be deployed but both the odoo and iotbox pods are not coming up unfortunately. They seem to be stuck in a "CrashLoopBackOff" status yet the postgres db pod is all up and working (on the face of it)

modonovan@cappaghodoo:~ $ sudo kubectl get pods --namespace pos -o wide
[sudo] password for modonovan:
NAME                      READY   STATUS             RESTARTS   AGE     IP           NODE          NOMINATED NODE   READINESS GATES
db-0                      1/1     Running            0          4h32m   10.42.0.12   cappaghodoo   <none>           <none>
iotbox-74588c5cfd-j9q5s   0/1     CrashLoopBackOff   56         4h32m   10.42.0.9    cappaghodoo   <none>           <none>
odoo-c84d5c575-zlfbk      0/1     CrashLoopBackOff   56         4h32m   10.42.0.13   cappaghodoo   <none>           <none>

Anything I need to be doing/editting to get these services to come up?

I also assume that I connect to the odoo server instance on say 10.42.0.13:8069 once it finally comes up - excuse the stupid question.

Thanks in advance

Mick

**Comment by tobru** [comment]
Thanks for trying. As stated in the README.md under "Disclaimer" I'm not able to provide user support, as this would blow up my free time (it really is a hobby project). It has been over a year since I last used and deployed this project, it could very well be that things broke along the way, the world turns fast. Sorry for that.

One time help and hints:
* Check the logs of the Pods, usually that describes why it doesn't work (kubectl logs...)
* Check the events of the Pods, could also help (kubectl describe pod ...)
* Consider to use Docker Compose if you're not familiar with Kubernetes - the learning curve is steep
* Check my words of warning about ARM support: https://github.com/tobru/odoo-pos-distribution#a-word-on-arm--raspberry-pi-support. You might have to build the images on your own to have runnable images for the architecture of Raspberry Pi 4

**Comment by modonovan** [comment]
Many thanks for the speedy response and hints.
